language: ruby
rvm:
- 2.1
  
# Containers are cool!  
sudo: false

install: 
- bundle install
- pip install --user awscli
- ~/.local/bin/aws configure set preview.cloudfront true
  
# Build and deploy the site to the S3 bucket on push to master, unless PR
script: bundle exec jekyll build
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id: AKIAICFJZ6K5DJCN3FDQ 
  secret_access_key:
    secure: "ggNAbKakB1FTTvpj/Qj4wYTDEEfNr9GDcl8g03mO+t2jFm+dAqrP3rAtgVRudaaCqdnh09cWB3CzvNF+2nFpEjRh8XvY9GcfborArElLDifwluIzq6elqqR7AtQ3qwlbXQT9aZU8c++hD+7lOw1amAzwkg5r/0oEmGBMxgVVITkbocLd1ZsDabi/gv4ONIVeo9wdRDeK+frzjQ5zOAij3SECmFUL4A06BwVE7ZJH/hqnOZ7x0kMfmLecNRkLTOQEcmzYbsAbCbWJze7f8mCvqS95f4PmLZTcOaVz8ZjCEX02y7Kvfevhc7ZHscTE9rjqyvXv1rXeSDS/e3QZuKK7Mr74vJcFG9JMWlPHfPsXeHE9DD4Tmq3ZrjTNeYZ9HmEpdeXeFzzQCk+PVF3y48wxrOST7UK/P/HUc9pqbbVSJv4c+DV8wvIyimIm61SxasQTzp3OjpatQoU2PWa7QtbGkBsJ/jM5ebVU2rcSEE+EkWKeLCBwUQlfr5gtyUL1x/VVLv0nKW8VVkM8HlPRy4QJ8rzpJw5UeATwI2qUnXl1djszjtpQyDGbGSw175U9nv99+/eqTnXZ1IlTRX0qFcCksWkhAJlKv7XHZ+WdzGf/jTEHjRtaQ0QpeJSm4vmgOStgb7efJce2I8iG90frpvzzrk/5dZl7z4TWo/OzwBRTm8E="
  bucket: blog-rust-lang-vn
  acl: public_read
  skip_cleanup: true
  local_dir: _site
  region: us-east-1
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false"

after_success: 
- '[[ $TRAVIS_PULL_REQUEST == "false" ]] && python invalidation-list.py'

after_deploy:
- '[[ $TRAVIS_PULL_REQUEST == "false" ]] && ~/.local/bin/aws cloudfront create-invalidation
  --invalidation-batch file://payload.json --distribution-id EZBISR7B1UL7J'
